# Introduction to DataFrames
**[Bogumił Kamiński](http://bogumilkaminski.pl/about/), Apr 6, 2018**

A brief introduction to basic usage of `DataFrames`. Tested under `DataFrames` *master* on 2018-04-06.
I will try to keep it up to date as the package evolves.

In [1]:
using DataFrames # load package
srand(1);

## Manipulating rows of DataFrame

### Reordering rows

In [2]:
x = DataFrame(id=1:10, x = rand(10), y = [zeros(5); ones(5)]) # and we hope that x[:x] is not sorted :)

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 1  │ 0.236033   │ 0.0 │
│ 2   │ 2  │ 0.346517   │ 0.0 │
│ 3   │ 3  │ 0.312707   │ 0.0 │
│ 4   │ 4  │ 0.00790928 │ 0.0 │
│ 5   │ 5  │ 0.488613   │ 0.0 │
│ 6   │ 6  │ 0.210968   │ 1.0 │
│ 7   │ 7  │ 0.951916   │ 1.0 │
│ 8   │ 8  │ 0.999905   │ 1.0 │
│ 9   │ 9  │ 0.251662   │ 1.0 │
│ 10  │ 10 │ 0.986666   │ 1.0 │

In [3]:
sort!(x, :x) # sort x in place

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 4  │ 0.00790928 │ 0.0 │
│ 2   │ 6  │ 0.210968   │ 1.0 │
│ 3   │ 1  │ 0.236033   │ 0.0 │
│ 4   │ 9  │ 0.251662   │ 1.0 │
│ 5   │ 3  │ 0.312707   │ 0.0 │
│ 6   │ 2  │ 0.346517   │ 0.0 │
│ 7   │ 5  │ 0.488613   │ 0.0 │
│ 8   │ 7  │ 0.951916   │ 1.0 │
│ 9   │ 10 │ 0.986666   │ 1.0 │
│ 10  │ 8  │ 0.999905   │ 1.0 │

In [4]:
y = sort(x, :id) # new DataFrame

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 1  │ 0.236033   │ 0.0 │
│ 2   │ 2  │ 0.346517   │ 0.0 │
│ 3   │ 3  │ 0.312707   │ 0.0 │
│ 4   │ 4  │ 0.00790928 │ 0.0 │
│ 5   │ 5  │ 0.488613   │ 0.0 │
│ 6   │ 6  │ 0.210968   │ 1.0 │
│ 7   │ 7  │ 0.951916   │ 1.0 │
│ 8   │ 8  │ 0.999905   │ 1.0 │
│ 9   │ 9  │ 0.251662   │ 1.0 │
│ 10  │ 10 │ 0.986666   │ 1.0 │

In [5]:
sort(x, (:y, :x), rev=(true, false))

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 6  │ 0.210968   │ 1.0 │
│ 2   │ 9  │ 0.251662   │ 1.0 │
│ 3   │ 7  │ 0.951916   │ 1.0 │
│ 4   │ 10 │ 0.986666   │ 1.0 │
│ 5   │ 8  │ 0.999905   │ 1.0 │
│ 6   │ 4  │ 0.00790928 │ 0.0 │
│ 7   │ 1  │ 0.236033   │ 0.0 │
│ 8   │ 3  │ 0.312707   │ 0.0 │
│ 9   │ 2  │ 0.346517   │ 0.0 │
│ 10  │ 5  │ 0.488613   │ 0.0 │

In [6]:
sort(x, (order(:y, rev=true), :x)) # the same as above

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 6  │ 0.210968   │ 1.0 │
│ 2   │ 9  │ 0.251662   │ 1.0 │
│ 3   │ 7  │ 0.951916   │ 1.0 │
│ 4   │ 10 │ 0.986666   │ 1.0 │
│ 5   │ 8  │ 0.999905   │ 1.0 │
│ 6   │ 4  │ 0.00790928 │ 0.0 │
│ 7   │ 1  │ 0.236033   │ 0.0 │
│ 8   │ 3  │ 0.312707   │ 0.0 │
│ 9   │ 2  │ 0.346517   │ 0.0 │
│ 10  │ 5  │ 0.488613   │ 0.0 │

In [7]:
sort(x, (order(:y, rev=true), order(:x, by=v->-v))) # some more fancy sorting stuff

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 8  │ 0.999905   │ 1.0 │
│ 2   │ 10 │ 0.986666   │ 1.0 │
│ 3   │ 7  │ 0.951916   │ 1.0 │
│ 4   │ 9  │ 0.251662   │ 1.0 │
│ 5   │ 6  │ 0.210968   │ 1.0 │
│ 6   │ 5  │ 0.488613   │ 0.0 │
│ 7   │ 2  │ 0.346517   │ 0.0 │
│ 8   │ 3  │ 0.312707   │ 0.0 │
│ 9   │ 1  │ 0.236033   │ 0.0 │
│ 10  │ 4  │ 0.00790928 │ 0.0 │

In [8]:
x[shuffle(1:10), :] # reorder rows (here randomly)

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 8  │ 0.999905   │ 1.0 │
│ 2   │ 10 │ 0.986666   │ 1.0 │
│ 3   │ 7  │ 0.951916   │ 1.0 │
│ 4   │ 2  │ 0.346517   │ 0.0 │
│ 5   │ 5  │ 0.488613   │ 0.0 │
│ 6   │ 1  │ 0.236033   │ 0.0 │
│ 7   │ 6  │ 0.210968   │ 1.0 │
│ 8   │ 9  │ 0.251662   │ 1.0 │
│ 9   │ 4  │ 0.00790928 │ 0.0 │
│ 10  │ 3  │ 0.312707   │ 0.0 │

In [9]:
sort!(x, :id)
x[[1,10],:] = x[[10,1],:] # swap rows
x

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 10 │ 0.986666   │ 1.0 │
│ 2   │ 2  │ 0.346517   │ 0.0 │
│ 3   │ 3  │ 0.312707   │ 0.0 │
│ 4   │ 4  │ 0.00790928 │ 0.0 │
│ 5   │ 5  │ 0.488613   │ 0.0 │
│ 6   │ 6  │ 0.210968   │ 1.0 │
│ 7   │ 7  │ 0.951916   │ 1.0 │
│ 8   │ 8  │ 0.999905   │ 1.0 │
│ 9   │ 9  │ 0.251662   │ 1.0 │
│ 10  │ 1  │ 0.236033   │ 0.0 │

In [10]:
x[1,:], x[10,:] = x[10,:], x[1,:] # and swap again
x

10×3 DataFrames.DataFrame
│ Row │ id │ x          │ y   │
├─────┼────┼────────────┼─────┤
│ 1   │ 1  │ 0.236033   │ 0.0 │
│ 2   │ 2  │ 0.346517   │ 0.0 │
│ 3   │ 3  │ 0.312707   │ 0.0 │
│ 4   │ 4  │ 0.00790928 │ 0.0 │
│ 5   │ 5  │ 0.488613   │ 0.0 │
│ 6   │ 6  │ 0.210968   │ 1.0 │
│ 7   │ 7  │ 0.951916   │ 1.0 │
│ 8   │ 8  │ 0.999905   │ 1.0 │
│ 9   │ 9  │ 0.251662   │ 1.0 │
│ 10  │ 10 │ 0.986666   │ 1.0 │

### Merging/adding rows

In [11]:
x = DataFrame(rand(3, 5))

3×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │

In [12]:
[x; x] # merge by rows - data frames must have the same column names; the same is vcat

6×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 6   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │

In [13]:
append!(x, x) # the same but modifies x

6×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 6   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │

In [14]:
push!(x, 1:5) # add one row to x at the end; must give correct number of values and correct types
x

7×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 6   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 7   │ 1.0       │ 2.0      │ 3.0       │ 4.0      │ 5.0      │

In [15]:
push!(x, Dict(:x1=> 11, :x2=> 12, :x3=> 13, :x4=> 14, :x5=> 15)) # also works with dictionaries
x

8×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 6   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 7   │ 1.0       │ 2.0      │ 3.0       │ 4.0      │ 5.0      │
│ 8   │ 11.0      │ 12.0     │ 13.0      │ 14.0     │ 15.0     │

### Subsetting/removing rows

In [16]:
x[1:2, :] # by index

2×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │

In [17]:
view(x, 1:2) # the same but a view

2×5 DataFrames.SubDataFrame{UnitRange{Int64}}
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │

In [18]:
x[repmat([true, false], 4), 1:3] # by Bool, exact length required

4×3 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │
├─────┼───────────┼──────────┼───────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │
│ 2   │ 0.46335   │ 0.976312 │ 0.455692  │
│ 3   │ 0.553206  │ 0.111981 │ 0.53803   │
│ 4   │ 1.0       │ 2.0      │ 3.0       │

In [19]:
view(x, repmat([true, false], 4), 1:3) # view again

4×3 DataFrames.SubDataFrame{Array{Int64,1}}
│ Row │ x1        │ x2       │ x3        │
├─────┼───────────┼──────────┼───────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │
│ 2   │ 0.46335   │ 0.976312 │ 0.455692  │
│ 3   │ 0.553206  │ 0.111981 │ 0.53803   │
│ 4   │ 1.0       │ 2.0      │ 3.0       │

In [20]:
deleterows!(x, 7) # delete one row

7×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 6   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 7   │ 11.0      │ 12.0     │ 13.0      │ 14.0     │ 15.0     │

In [21]:
deleterows!(x, 6:7) # delete collection of rows

5×5 DataFrames.DataFrame
│ Row │ x1        │ x2       │ x3        │ x4       │ x5       │
├─────┼───────────┼──────────┼───────────┼──────────┼──────────┤
│ 1   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 2   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │
│ 3   │ 0.46335   │ 0.976312 │ 0.455692  │ 0.548983 │ 0.648054 │
│ 4   │ 0.0856352 │ 0.185821 │ 0.0516146 │ 0.279395 │ 0.370971 │
│ 5   │ 0.553206  │ 0.111981 │ 0.53803   │ 0.178246 │ 0.894166 │

In [22]:
x = DataFrame([1:4, 2:5, 3:6])

4×3 DataFrames.DataFrame
│ Row │ x1 │ x2 │ x3 │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 2  │ 3  │
│ 2   │ 2  │ 3  │ 4  │
│ 3   │ 3  │ 4  │ 5  │
│ 4   │ 4  │ 5  │ 6  │

In [23]:
filter(r -> r[:x1] > 2.5, x) # create a new DataFrame where filtering function operates on DataFrameRow

2×3 DataFrames.DataFrame
│ Row │ x1 │ x2 │ x3 │
├─────┼────┼────┼────┤
│ 1   │ 3  │ 4  │ 5  │
│ 2   │ 4  │ 5  │ 6  │

In [24]:
# in place modification of x, an example with do-block syntax
filter!(x) do r
    if r[:x1] > 2.5
        return r[:x2] < 4.5
    end
    r[:x3] < 3.5
end

2×3 DataFrames.DataFrame
│ Row │ x1 │ x2 │ x3 │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 2  │ 3  │
│ 2   │ 3  │ 4  │ 5  │

### Deduplicating

In [25]:
x = DataFrame(A=[1,2], B=["x","y"])
append!(x, x)
x[:C] = 1:4
x

4×3 DataFrames.DataFrame
│ Row │ A │ B │ C │
├─────┼───┼───┼───┤
│ 1   │ 1 │ x │ 1 │
│ 2   │ 2 │ y │ 2 │
│ 3   │ 1 │ x │ 3 │
│ 4   │ 2 │ y │ 4 │

In [26]:
unique(x, [1,2]) # get first unique rows for given index

2×3 DataFrames.DataFrame
│ Row │ A │ B │ C │
├─────┼───┼───┼───┤
│ 1   │ 1 │ x │ 1 │
│ 2   │ 2 │ y │ 2 │

In [27]:
unique(x) # now we look at whole rows

4×3 DataFrames.DataFrame
│ Row │ A │ B │ C │
├─────┼───┼───┼───┤
│ 1   │ 1 │ x │ 1 │
│ 2   │ 2 │ y │ 2 │
│ 3   │ 1 │ x │ 3 │
│ 4   │ 2 │ y │ 4 │

In [28]:
nonunique(x, :A) # get indicators of non-unique rows

4-element Array{Bool,1}:
 false
 false
  true
  true

In [29]:
unique!(x, :B) # modify x in place

2×3 DataFrames.DataFrame
│ Row │ A │ B │ C │
├─────┼───┼───┼───┤
│ 1   │ 1 │ x │ 1 │
│ 2   │ 2 │ y │ 2 │

### Extracting one row from `DataFrame`

In [30]:
x = DataFrame(x=[1,missing,2], y=["a", "b", missing], z=[true,false,true])
cols = [:x, :y]
[x[1, col] for col in cols] # subset of columns

2-element Array{Any,1}:
 1   
  "a"

In [31]:
[[x[i, col] for col in names(x)] for i in 1:nrow(x)] # vector of vectors, each entry contains one full row of x

3-element Array{Array{Any,1},1}:
 Any[1, "a", true]       
 Any[missing, "b", false]
 Any[2, missing, true]   

In [32]:
Tuple(x[1, col] for col in cols) # similar construct for Tuples, when ported to Julia 0.7 NamedTuples will be added

(1, "a")