# Introduction to DataFrames
**[Bogumił Kamiński](http://bogumilkaminski.pl/about/), February 13, 2023**

In [1]:
using DataFrames

## Split-apply-combine

### Grouping a data frame

In [2]:
x = DataFrame(id=[1,2,3,4,1,2,3,4], id2=[1,2,1,2,1,2,1,2], v=rand(8))

8×3 DataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     2      2  0.179636
   3 │     3      1  0.856131
   4 │     4      2  0.532306
   5 │     1      1  0.24277
   6 │     2      2  0.747279
   7 │     3      1  0.476843
   8 │     4      2  0.542538

In [3]:
groupby(x, :id)

GroupedDataFrame with 4 groups based on key: id
First Group (2 rows): id = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277
⋮
Last Group (2 rows): id = 4
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.532306
   2 │     4      2  0.542538

In [4]:
groupby(x, [])

GroupedDataFrame with 1 group based on key: 
First Group (8 rows): 
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     2      2  0.179636
   3 │     3      1  0.856131
   4 │     4      2  0.532306
   5 │     1      1  0.24277
   6 │     2      2  0.747279
   7 │     3      1  0.476843
   8 │     4      2  0.542538

In [5]:
gx2 = groupby(x, [:id, :id2])

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.532306
   2 │     4      2  0.542538

In [6]:
parent(gx2) # get the parent DataFrame 

8×3 DataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     2      2  0.179636
   3 │     3      1  0.856131
   4 │     4      2  0.532306
   5 │     1      1  0.24277
   6 │     2      2  0.747279
   7 │     3      1  0.476843
   8 │     4      2  0.542538

In [7]:
vcat(gx2...) # back to the DataFrame, but in a different order of rows than the original

8×3 DataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277
   3 │     2      2  0.179636
   4 │     2      2  0.747279
   5 │     3      1  0.856131
   6 │     3      1  0.476843
   7 │     4      2  0.532306
   8 │     4      2  0.542538

In [8]:
DataFrame(gx2) # the same

8×3 DataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277
   3 │     2      2  0.179636
   4 │     2      2  0.747279
   5 │     3      1  0.856131
   6 │     3      1  0.476843
   7 │     4      2  0.532306
   8 │     4      2  0.542538

In [9]:
DataFrame(gx2, keepkeys=false) # drop grouping columns when creating a data frame

8×1 DataFrame
 Row │ v        
     │ Float64  
─────┼──────────
   1 │ 0.239786
   2 │ 0.24277
   3 │ 0.179636
   4 │ 0.747279
   5 │ 0.856131
   6 │ 0.476843
   7 │ 0.532306
   8 │ 0.542538

In [10]:
groupcols(gx2) # vector of names of grouping variables

2-element Vector{Symbol}:
 :id
 :id2

In [11]:
valuecols(gx2) # and non-grouping variables

1-element Vector{Symbol}:
 :v

In [12]:
groupindices(gx2) # group indices in parent(gx2)

8-element Vector{Union{Missing, Int64}}:
 1
 2
 3
 4
 1
 2
 3
 4

In [13]:
kgx2 = keys(gx2)

4-element DataFrames.GroupKeys{GroupedDataFrame{DataFrame}}:
 GroupKey: (id = 1, id2 = 1)
 GroupKey: (id = 2, id2 = 2)
 GroupKey: (id = 3, id2 = 1)
 GroupKey: (id = 4, id2 = 2)

You can index into a `GroupedDataFrame` like to a vector or to a dictionary.
The second form acceps `GroupKey`, `NamedTuple` or a `Tuple`

In [14]:
gx2

GroupedDataFrame with 4 groups based on keys: id, id2
First Group (2 rows): id = 1, id2 = 1
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277
⋮
Last Group (2 rows): id = 4, id2 = 2
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     4      2  0.532306
   2 │     4      2  0.542538

In [15]:
k = keys(gx2)[1]

GroupKey: (id = 1, id2 = 1)

In [16]:
ntk = NamedTuple(k)

(id = 1, id2 = 1)

In [17]:
tk = Tuple(k)

(1, 1)

the operations below produce the same result and are fast

In [18]:
gx2[1]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277

In [19]:
gx2[k]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277

In [20]:
gx2[ntk]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277

In [21]:
gx2[tk]

2×3 SubDataFrame
 Row │ id     id2    v        
     │ Int64  Int64  Float64  
─────┼────────────────────────
   1 │     1      1  0.239786
   2 │     1      1  0.24277

handling missing values

In [22]:
x = DataFrame(id = [missing, 5, 1, 3, missing], x = 1:5)

5×2 DataFrame
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │       5      2
   3 │       1      3
   4 │       3      4
   5 │ missing      5

In [23]:
groupby(x, :id) # by default groups include mising values and their order is not guaranteed

GroupedDataFrame with 4 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (2 rows): id = missing
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │ missing      5

In [24]:
groupby(x, :id, sort=true, skipmissing=true) # but we can change it; now they are sorted

GroupedDataFrame with 3 groups based on key: id
First Group (1 row): id = 1
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      1      3
⋮
Last Group (1 row): id = 5
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      5      2

In [25]:
groupby(x, :id, sort=false) # and now they are in the order they appear in the source data frame

GroupedDataFrame with 4 groups based on key: id
First Group (2 rows): id = missing
 Row │ id       x     
     │ Int64?   Int64 
─────┼────────────────
   1 │ missing      1
   2 │ missing      5
⋮
Last Group (1 row): id = 3
 Row │ id      x     
     │ Int64?  Int64 
─────┼───────────────
   1 │      3      4

### Performing transformations by group using `combine`, `select`, `select!`, `transform`, and `transform!`

In [26]:
using Statistics
using Chain

In [27]:
x = DataFrame(id=rand('a':'d', 100), v=rand(100))

100×2 DataFrame
 Row │ id    v         
     │ Char  Float64   
─────┼─────────────────
   1 │ a     0.729846
   2 │ b     0.978141
   3 │ d     0.180073
   4 │ c     0.264876
   5 │ d     0.583029
   6 │ c     0.773974
   7 │ a     0.993063
   8 │ c     0.109659
   9 │ d     0.753735
  10 │ c     0.540383
  11 │ b     0.112203
  ⋮  │  ⋮        ⋮
  91 │ c     0.814132
  92 │ d     0.668003
  93 │ d     0.0452986
  94 │ d     0.0298229
  95 │ c     0.197737
  96 │ b     0.429591
  97 │ d     0.726327
  98 │ b     0.694146
  99 │ c     0.96734
 100 │ d     0.843926
        79 rows omitted

In [28]:
# apply a function to each group of a data frame
# combine keeps as many rows as are returned from the function
@chain x begin
    groupby(:id)
    combine(:v => mean)
end

4×2 DataFrame
 Row │ id    v_mean   
     │ Char  Float64  
─────┼────────────────
   1 │ a     0.523705
   2 │ b     0.591953
   3 │ d     0.511306
   4 │ c     0.469842

In [29]:
x.id2 = axes(x, 1)

Base.OneTo(100)

In [30]:
# select and transform keep as many rows as are in the source data frame and in correct order
# additionally transform keeps all columns from the source
@chain x begin
    groupby(:id)
    transform(:v => mean)
end

100×4 DataFrame
 Row │ id    v          id2    v_mean   
     │ Char  Float64    Int64  Float64  
─────┼──────────────────────────────────
   1 │ a     0.729846       1  0.523705
   2 │ b     0.978141       2  0.591953
   3 │ d     0.180073       3  0.511306
   4 │ c     0.264876       4  0.469842
   5 │ d     0.583029       5  0.511306
   6 │ c     0.773974       6  0.469842
   7 │ a     0.993063       7  0.523705
   8 │ c     0.109659       8  0.469842
   9 │ d     0.753735       9  0.511306
  10 │ c     0.540383      10  0.469842
  11 │ b     0.112203      11  0.591953
  ⋮  │  ⋮        ⋮        ⋮       ⋮
  91 │ c     0.814132      91  0.469842
  92 │ d     0.668003      92  0.511306
  93 │ d     0.0452986     93  0.511306
  94 │ d     0.0298229     94  0.511306
  95 │ c     0.197737      95  0.469842
  96 │ b     0.429591      96  0.591953
  97 │ d     0.726327      97  0.511306
  98 │ b     0.694146      98  0.591953
  99 │ c     0.96734       99  0.469842
 100 │ d     0.843926     100  0.511306
                         79 rows omitted

In [31]:
# note that combine reorders rows by group of GroupedDataFrame
@chain x begin
    groupby(:id)
    combine(:id2, :v => mean)
end

100×3 DataFrame
 Row │ id    id2    v_mean   
     │ Char  Int64  Float64  
─────┼───────────────────────
   1 │ a         1  0.523705
   2 │ a         7  0.523705
   3 │ a        15  0.523705
   4 │ a        21  0.523705
   5 │ a        23  0.523705
   6 │ a        26  0.523705
   7 │ a        30  0.523705
   8 │ a        34  0.523705
   9 │ a        40  0.523705
  10 │ a        41  0.523705
  11 │ a        50  0.523705
  ⋮  │  ⋮      ⋮       ⋮
  91 │ c        49  0.469842
  92 │ c        56  0.469842
  93 │ c        65  0.469842
  94 │ c        74  0.469842
  95 │ c        85  0.469842
  96 │ c        86  0.469842
  97 │ c        90  0.469842
  98 │ c        91  0.469842
  99 │ c        95  0.469842
 100 │ c        99  0.469842
              79 rows omitted

In [32]:
# we give a custom name for the result column
@chain x begin
    groupby(:id)
    combine(:v => mean => :res)
end

4×2 DataFrame
 Row │ id    res      
     │ Char  Float64  
─────┼────────────────
   1 │ a     0.523705
   2 │ b     0.591953
   3 │ d     0.511306
   4 │ c     0.469842

In [33]:
# you can have multiple operations
@chain x begin
    groupby(:id)
    combine(:v => mean => :res1, :v => sum => :res2, nrow => :n)
end

4×4 DataFrame
 Row │ id    res1      res2     n     
     │ Char  Float64   Float64  Int64 
─────┼────────────────────────────────
   1 │ a     0.523705  12.5689     24
   2 │ b     0.591953  15.9827     27
   3 │ d     0.511306  13.8053     27
   4 │ c     0.469842  10.3365     22

Additional notes:
* `select!` and `transform!` perform operations in-place
* The general syntax for transformation is `source_columns => function => target_column`
* if you pass multiple columns to a function they are treated as positional arguments
* `ByRow` and `AsTable` work exactly like discussed for operations on data frames in 05_columns.ipynb
* you can automatically groupby again the result of `combine`, `select` etc. by passing `ungroup=false` keyword argument to them
* similarly `keepkeys` keyword argument allows you to drop grouping columns from the resulting data frame

It is also allowed to pass a function to all these functions (also - as a special case, as a first argument). In this case the return value can be a table. In particular it allows for an easy dropping of groups if you return an empty table from the function.

If you pass a function you can use a `do` block syntax. In case of passing a function it gets a `SubDataFrame` as its argument.

Here is an example:

In [34]:
combine(groupby(x, :id)) do sdf
    n = nrow(sdf)
    n < 25 ? DataFrame() : DataFrame(n=n) # drop groups with low number of rows
end

2×2 DataFrame
 Row │ id    n     
     │ Char  Int64 
─────┼─────────────
   1 │ b        27
   2 │ d        27

You can also produce multiple columns in a single operation, e.g.:

In [35]:
df = DataFrame(id=[1,1,2,2], val=[1,2,3,4])

4×2 DataFrame
 Row │ id     val   
     │ Int64  Int64 
─────┼──────────────
   1 │     1      1
   2 │     1      2
   3 │     2      3
   4 │     2      4

In [36]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => AsTable)
end

2×3 DataFrame
 Row │ id     x1     x2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

In [37]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => [:c1, :c2])
end

2×3 DataFrame
 Row │ id     c1     c2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      2
   2 │     2      3      4

It is easy to unnest the column into multiple columns, e.g.

In [38]:
df = DataFrame(a=[(p=1, q=2), (p=3, q=4)])

2×1 DataFrame
 Row │ a              
     │ NamedTup…      
─────┼────────────────
   1 │ (p = 1, q = 2)
   2 │ (p = 3, q = 4)

In [39]:
select(df, :a => AsTable)

2×2 DataFrame
 Row │ p      q     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

In [40]:
df = DataFrame(a=[[1, 2], [3, 4]])

2×1 DataFrame
 Row │ a      
     │ Array… 
─────┼────────
   1 │ [1, 2]
   2 │ [3, 4]

In [41]:
select(df, :a => AsTable) # automatic column names generated

2×2 DataFrame
 Row │ x1     x2    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

In [42]:
select(df, :a => [:C1, :C2]) # custom column names generated

2×2 DataFrame
 Row │ C1     C2    
     │ Int64  Int64 
─────┼──────────────
   1 │     1      2
   2 │     3      4

Finally, observe that one can conveniently apply multiple transformations using broadcasting:

In [43]:
df = DataFrame(id=repeat(1:10, 10), x1=1:100, x2=101:200)

100×3 DataFrame
 Row │ id     x1     x2    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1    101
   2 │     2      2    102
   3 │     3      3    103
   4 │     4      4    104
   5 │     5      5    105
   6 │     6      6    106
   7 │     7      7    107
   8 │     8      8    108
   9 │     9      9    109
  10 │    10     10    110
  11 │     1     11    111
  ⋮  │   ⋮      ⋮      ⋮
  91 │     1     91    191
  92 │     2     92    192
  93 │     3     93    193
  94 │     4     94    194
  95 │     5     95    195
  96 │     6     96    196
  97 │     7     97    197
  98 │     8     98    198
  99 │     9     99    199
 100 │    10    100    200
            79 rows omitted

In [44]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> minimum)
end

10×3 DataFrame
 Row │ id     x1_minimum  x2_minimum 
     │ Int64  Int64       Int64      
─────┼───────────────────────────────
   1 │     1           1         101
   2 │     2           2         102
   3 │     3           3         103
   4 │     4           4         104
   5 │     5           5         105
   6 │     6           6         106
   7 │     7           7         107
   8 │     8           8         108
   9 │     9           9         109
  10 │    10          10         110

In [45]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> [minimum maximum])
end

10×5 DataFrame
 Row │ id     x1_minimum  x2_minimum  x1_maximum  x2_maximum 
     │ Int64  Int64       Int64       Int64       Int64      
─────┼───────────────────────────────────────────────────────
   1 │     1           1         101          91         191
   2 │     2           2         102          92         192
   3 │     3           3         103          93         193
   4 │     4           4         104          94         194
   5 │     5           5         105          95         195
   6 │     6           6         106          96         196
   7 │     7           7         107          97         197
   8 │     8           8         108          98         198
   9 │     9           9         109          99         199
  10 │    10          10         110         100         200

### Aggregation of a data frame using `mapcols`

In [46]:
x = DataFrame(rand(10, 10), :auto)

10×10 DataFrame
 Row │ x1         x2        x3        x4           x5         x6         x7    ⋯
     │ Float64    Float64   Float64   Float64      Float64    Float64    Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.793935   0.45687   0.907089  0.351164     0.468913   0.438825   0.680 ⋯
   2 │ 0.387642   0.881526  0.776264  0.295657     0.629058   0.57288    0.751
   3 │ 0.0588001  0.448813  0.811436  0.0117327    0.424192   0.420064   0.122
   4 │ 0.0149787  0.55115   0.864966  0.23952      0.598431   0.919414   0.016
   5 │ 0.393852   0.263755  0.457996  0.122174     0.152931   0.0982895  0.926 ⋯
   6 │ 0.825976   0.112791  0.3081    0.000525589  0.909336   0.340167   0.228
   7 │ 0.553853   0.689573  0.15967   0.856762     0.518455   0.675691   0.538
   8 │ 0.825157   0.8904    0.481969  0.0589375    0.0665701  0.858516   0.157
   9 │ 0.839455   0.564254  0.178448  0.727648     0.483625   0.903504   0.459 ⋯
  10 │ 0.3542     0.488556  0.468679  0.691836     0.448638   0.872127   0.696
                                                               4 columns omitted

In [47]:
mapcols(mean, x)

1×10 DataFrame
 Row │ x1        x2        x3        x4        x5        x6        x7        x ⋯
     │ Float64   Float64   Float64   Float64   Float64   Float64   Float64   F ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.504785  0.534769  0.541462  0.335596  0.470015  0.609948  0.457739  0 ⋯
                                                               3 columns omitted

### Mapping rows and columns using `eachcol` and `eachrow`

In [48]:
map(mean, eachcol(x)) # map a function over each column and return a vector

10-element Vector{Float64}:
 0.504784841417523
 0.5347688352920631
 0.5414617940852021
 0.3355955804813384
 0.4700149148775635
 0.6099479022673252
 0.4577392326685229
 0.57937264963089
 0.45202385337967466
 0.3791468806271661

In [49]:
# an iteration returns a Pair with column name and values
foreach(c -> println(c[1], ": ", mean(c[2])), pairs(eachcol(x)))

x1: 0.504784841417523
x2: 0.5347688352920631
x3: 0.5414617940852021
x4: 0.3355955804813384
x5: 0.4700149148775635
x6: 0.6099479022673252
x7: 0.4577392326685229
x8: 0.57937264963089
x9: 0.45202385337967466
x10: 0.3791468806271661


In [50]:
# now the returned value is DataFrameRow which works as a NamedTuple but is a view to a parent DataFrame
map(r -> r.x1/r.x2, eachrow(x))

10-element Vector{Float64}:
 1.737770179560276
 0.4397392873188234
 0.13101271017638122
 0.027177156050721477
 1.4932473184688198
 7.323092180729385
 0.8031817580079057
 0.9267256635293967
 1.4877250440295864
 0.7249933549150893

In [51]:
# it prints like a data frame, only the caption is different so that you know the type of the object
er = eachrow(x)

10×10 DataFrameRows
 Row │ x1         x2        x3        x4           x5         x6         x7    ⋯
     │ Float64    Float64   Float64   Float64      Float64    Float64    Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.793935   0.45687   0.907089  0.351164     0.468913   0.438825   0.680 ⋯
   2 │ 0.387642   0.881526  0.776264  0.295657     0.629058   0.57288    0.751
   3 │ 0.0588001  0.448813  0.811436  0.0117327    0.424192   0.420064   0.122
   4 │ 0.0149787  0.55115   0.864966  0.23952      0.598431   0.919414   0.016
   5 │ 0.393852   0.263755  0.457996  0.122174     0.152931   0.0982895  0.926 ⋯
   6 │ 0.825976   0.112791  0.3081    0.000525589  0.909336   0.340167   0.228
   7 │ 0.553853   0.689573  0.15967   0.856762     0.518455   0.675691   0.538
   8 │ 0.825157   0.8904    0.481969  0.0589375    0.0665701  0.858516   0.157
   9 │ 0.839455   0.564254  0.178448  0.727648     0.483625   0.903504   0.459 ⋯
  10 │ 0.3542     0.488556  0.468679  0.691836     0.448638   0.872127   0.696
                                                               4 columns omitted

In [52]:
er.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.793935382423837
 0.38764175810388546
 0.058800146945729326
 0.014978679608386947
 0.3938518572622478
 0.8259762402778601
 0.5538525731101662
 0.8251566133725446
 0.8394550502957067
 0.3542001127748666

In [53]:
# it prints like a data frame, only the caption is different so that you know the type of the object
ec = eachcol(x)

10×10 DataFrameColumns
 Row │ x1         x2        x3        x4           x5         x6         x7    ⋯
     │ Float64    Float64   Float64   Float64      Float64    Float64    Float ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.793935   0.45687   0.907089  0.351164     0.468913   0.438825   0.680 ⋯
   2 │ 0.387642   0.881526  0.776264  0.295657     0.629058   0.57288    0.751
   3 │ 0.0588001  0.448813  0.811436  0.0117327    0.424192   0.420064   0.122
   4 │ 0.0149787  0.55115   0.864966  0.23952      0.598431   0.919414   0.016
   5 │ 0.393852   0.263755  0.457996  0.122174     0.152931   0.0982895  0.926 ⋯
   6 │ 0.825976   0.112791  0.3081    0.000525589  0.909336   0.340167   0.228
   7 │ 0.553853   0.689573  0.15967   0.856762     0.518455   0.675691   0.538
   8 │ 0.825157   0.8904    0.481969  0.0589375    0.0665701  0.858516   0.157
   9 │ 0.839455   0.564254  0.178448  0.727648     0.483625   0.903504   0.459 ⋯
  10 │ 0.3542     0.488556  0.468679  0.691836     0.448638   0.872127   0.696
                                                               4 columns omitted

In [54]:
ec.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.793935382423837
 0.38764175810388546
 0.058800146945729326
 0.014978679608386947
 0.3938518572622478
 0.8259762402778601
 0.5538525731101662
 0.8251566133725446
 0.8394550502957067
 0.3542001127748666

### Transposing

you can transpose a data frame using `permutedims`:

In [55]:
df = DataFrame(reshape(1:12, 3, 4), :auto)

3×4 DataFrame
 Row │ x1     x2     x3     x4    
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      4      7     10
   2 │     2      5      8     11
   3 │     3      6      9     12

In [56]:
permutedims(df)

4×3 DataFrame
 Row │ x1     x2     x3    
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      2      3
   2 │     4      5      6
   3 │     7      8      9
   4 │    10     11     12

In [57]:
df.names = ["a", "b", "c"]

3-element Vector{String}:
 "a"
 "b"
 "c"

In [58]:
permutedims(df, :names)

4×4 DataFrame
 Row │ names   a      b      c     
     │ String  Int64  Int64  Int64 
─────┼─────────────────────────────
   1 │ x1          1      2      3
   2 │ x2          4      5      6
   3 │ x3          7      8      9
   4 │ x4         10     11     12