# Introduction to DataFrames
**[Bogumił Kamiński](http://bogumilkaminski.pl/about/), September 12, 2026**

In [1]:
using DataFrames

## Split-apply-combine

### Grouping a data frame

In [2]:
x = DataFrame(id=[1,2,3,4,1,2,3,4], id2=[1,2,1,2,1,2,1,2], v=rand(8))

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,2,2,0.526733
3,3,1,0.57569
4,4,2,0.808356
5,1,1,0.65009
6,2,2,0.505178
7,3,1,0.903473
8,4,2,0.810646


In [3]:
groupby(x, :id)

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009
Row,id,id2,v
,Int64,Int64,Float64
1,4,2,0.808356
2,4,2,0.810646


In [4]:
groupby(x, [])

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,2,2,0.526733
3,3,1,0.57569
4,4,2,0.808356
5,1,1,0.65009
6,2,2,0.505178
7,3,1,0.903473
8,4,2,0.810646


In [5]:
gx2 = groupby(x, [:id, :id2])

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009
Row,id,id2,v
,Int64,Int64,Float64
1,4,2,0.808356
2,4,2,0.810646


In [6]:
parent(gx2) # get the parent DataFrame 

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,2,2,0.526733
3,3,1,0.57569
4,4,2,0.808356
5,1,1,0.65009
6,2,2,0.505178
7,3,1,0.903473
8,4,2,0.810646


In [7]:
vcat(gx2...) # back to the DataFrame, but in a different order of rows than the original

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009
3,2,2,0.526733
4,2,2,0.505178
5,3,1,0.57569
6,3,1,0.903473
7,4,2,0.808356
8,4,2,0.810646


In [8]:
DataFrame(gx2) # the same

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009
3,2,2,0.526733
4,2,2,0.505178
5,3,1,0.57569
6,3,1,0.903473
7,4,2,0.808356
8,4,2,0.810646


In [9]:
DataFrame(gx2, keepkeys=false) # drop grouping columns when creating a data frame

Row,v
,Float64
1,0.813423
2,0.65009
3,0.526733
4,0.505178
5,0.57569
6,0.903473
7,0.808356
8,0.810646


In [10]:
groupcols(gx2) # vector of names of grouping variables

2-element Vector{Symbol}:
 :id
 :id2

In [11]:
valuecols(gx2) # and non-grouping variables

1-element Vector{Symbol}:
 :v

In [12]:
groupindices(gx2) # group indices in parent(gx2)

8-element Vector{Union{Missing, Int64}}:
 1
 2
 3
 4
 1
 2
 3
 4

In [13]:
kgx2 = keys(gx2)

4-element DataFrames.GroupKeys{GroupedDataFrame{DataFrame}}:
 GroupKey: (id = 1, id2 = 1)
 GroupKey: (id = 2, id2 = 2)
 GroupKey: (id = 3, id2 = 1)
 GroupKey: (id = 4, id2 = 2)

You can index into a `GroupedDataFrame` like to a vector or to a dictionary.
The second form acceps `GroupKey`, `NamedTuple` or a `Tuple`

In [14]:
gx2

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009
Row,id,id2,v
,Int64,Int64,Float64
1,4,2,0.808356
2,4,2,0.810646


In [15]:
k = keys(gx2)[1]

GroupKey: (id = 1, id2 = 1)

In [16]:
ntk = NamedTuple(k)

(id = 1, id2 = 1)

In [17]:
tk = Tuple(k)

(1, 1)

the operations below produce the same result and are fast

In [18]:
gx2[1]

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009


In [19]:
gx2[k]

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009


In [20]:
gx2[ntk]

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009


In [21]:
gx2[tk]

Row,id,id2,v
,Int64,Int64,Float64
1,1,1,0.813423
2,1,1,0.65009


handling missing values

In [22]:
x = DataFrame(id = [missing, 5, 1, 3, missing], x = 1:5)

Row,id,x
,Int64?,Int64
1,missing,1
2,5,2
3,1,3
4,3,4
5,missing,5


In [23]:
groupby(x, :id) # by default groups include mising values and their order is not guaranteed

Row,id,x
,Int64?,Int64
1,1,3
Row,id,x
,Int64?,Int64
1,missing,1
2,missing,5


In [24]:
groupby(x, :id, sort=true, skipmissing=true) # but we can change it; now they are sorted

Row,id,x
,Int64?,Int64
1,1,3
Row,id,x
,Int64?,Int64
1,5,2


In [25]:
groupby(x, :id, sort=false) # and now they are in the order they appear in the source data frame

Row,id,x
,Int64?,Int64
1,missing,1
2,missing,5
Row,id,x
,Int64?,Int64
1,3,4


### Performing transformations by group using `combine`, `select`, `select!`, `transform`, and `transform!`

In [26]:
using Statistics
using Chain

In [27]:
x = DataFrame(id=rand('a':'d', 100), v=rand(100))

Row,id,v
,Char,Float64
1,c,0.19525
2,d,0.951071
3,b,0.829897
4,c,0.936981
5,c,0.22682
6,c,0.200683
7,b,0.467185
8,b,0.643974
9,d,0.799861


In [28]:
# apply a function to each group of a data frame
# combine keeps as many rows as are returned from the function
@chain x begin
    groupby(:id)
    combine(:v => mean)
end

Row,id,v_mean
,Char,Float64
1,c,0.52349
2,d,0.566497
3,b,0.605831
4,a,0.527807


In [29]:
x.id2 = axes(x, 1)

Base.OneTo(100)

In [30]:
# select and transform keep as many rows as are in the source data frame and in correct order
# additionally transform keeps all columns from the source
@chain x begin
    groupby(:id)
    transform(:v => mean)
end

Row,id,v,id2,v_mean
,Char,Float64,Int64,Float64
1,c,0.19525,1,0.52349
2,d,0.951071,2,0.566497
3,b,0.829897,3,0.605831
4,c,0.936981,4,0.52349
5,c,0.22682,5,0.52349
6,c,0.200683,6,0.52349
7,b,0.467185,7,0.605831
8,b,0.643974,8,0.605831
9,d,0.799861,9,0.566497


In [31]:
# note that combine reorders rows by group of GroupedDataFrame
@chain x begin
    groupby(:id)
    combine(:id2, :v => mean)
end

Row,id,id2,v_mean
,Char,Int64,Float64
1,c,1,0.52349
2,c,4,0.52349
3,c,5,0.52349
4,c,6,0.52349
5,c,10,0.52349
6,c,15,0.52349
7,c,16,0.52349
8,c,20,0.52349
9,c,21,0.52349


In [32]:
# we give a custom name for the result column
@chain x begin
    groupby(:id)
    combine(:v => mean => :res)
end

Row,id,res
,Char,Float64
1,c,0.52349
2,d,0.566497
3,b,0.605831
4,a,0.527807


In [33]:
# you can have multiple operations
@chain x begin
    groupby(:id)
    combine(:v => mean => :res1, :v => sum => :res2, nrow => :n)
end

Row,id,res1,res2,n
,Char,Float64,Float64,Int64
1,c,0.52349,12.5637,24
2,d,0.566497,10.7634,19
3,b,0.605831,16.3574,27
4,a,0.527807,15.8342,30


Additional notes:
* `select!` and `transform!` perform operations in-place
* The general syntax for transformation is `source_columns => function => target_column`
* if you pass multiple columns to a function they are treated as positional arguments
* `ByRow` and `AsTable` work exactly like discussed for operations on data frames in 05_columns.ipynb
* you can automatically groupby again the result of `combine`, `select` etc. by passing `ungroup=false` keyword argument to them
* similarly `keepkeys` keyword argument allows you to drop grouping columns from the resulting data frame

It is also allowed to pass a function to all these functions (also - as a special case, as a first argument). In this case the return value can be a table. In particular it allows for an easy dropping of groups if you return an empty table from the function.

If you pass a function you can use a `do` block syntax. In case of passing a function it gets a `SubDataFrame` as its argument.

Here is an example:

In [34]:
combine(groupby(x, :id)) do sdf
    n = nrow(sdf)
    n < 25 ? DataFrame() : DataFrame(n=n) # drop groups with low number of rows
end

Row,id,n
,Char,Int64
1,b,27
2,a,30


You can also produce multiple columns in a single operation, e.g.:

In [35]:
df = DataFrame(id=[1,1,2,2], val=[1,2,3,4])

Row,id,val
,Int64,Int64
1,1,1
2,1,2
3,2,3
4,2,4


In [36]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => AsTable)
end

Row,id,x1,x2
,Int64,Int64,Int64
1,1,1,2
2,2,3,4


In [37]:
@chain df begin
    groupby(:id)
    combine(:val => (x -> [x]) => [:c1, :c2])
end

Row,id,c1,c2
,Int64,Int64,Int64
1,1,1,2
2,2,3,4


It is easy to unnest the column into multiple columns, e.g.

In [38]:
df = DataFrame(a=[(p=1, q=2), (p=3, q=4)])

Row,a
,NamedTup…
1,"(p = 1, q = 2)"
2,"(p = 3, q = 4)"


In [39]:
select(df, :a => AsTable)

Row,p,q
,Int64,Int64
1,1,2
2,3,4


In [40]:
df = DataFrame(a=[[1, 2], [3, 4]])

Row,a
,Array…
1,"[1, 2]"
2,"[3, 4]"


In [41]:
select(df, :a => AsTable) # automatic column names generated

Row,x1,x2
,Int64,Int64
1,1,2
2,3,4


In [42]:
select(df, :a => [:C1, :C2]) # custom column names generated

Row,C1,C2
,Int64,Int64
1,1,2
2,3,4


Finally, observe that one can conveniently apply multiple transformations using broadcasting:

In [43]:
df = DataFrame(id=repeat(1:10, 10), x1=1:100, x2=101:200)

Row,id,x1,x2
,Int64,Int64,Int64
1,1,1,101
2,2,2,102
3,3,3,103
4,4,4,104
5,5,5,105
6,6,6,106
7,7,7,107
8,8,8,108
9,9,9,109


In [44]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> minimum)
end

Row,id,x1_minimum,x2_minimum
,Int64,Int64,Int64
1,1,1,101
2,2,2,102
3,3,3,103
4,4,4,104
5,5,5,105
6,6,6,106
7,7,7,107
8,8,8,108
9,9,9,109


In [45]:
@chain df begin
    groupby(:id)
    combine([:x1, :x2] .=> [minimum maximum])
end

Row,id,x1_minimum,x2_minimum,x1_maximum,x2_maximum
,Int64,Int64,Int64,Int64,Int64
1,1,1,101,91,191
2,2,2,102,92,192
3,3,3,103,93,193
4,4,4,104,94,194
5,5,5,105,95,195
6,6,6,106,96,196
7,7,7,107,97,197
8,8,8,108,98,198
9,9,9,109,99,199


### Aggregation of a data frame using `mapcols`

In [46]:
x = DataFrame(rand(10, 10), :auto)

Row,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64
1,0.634498,0.450796,0.364021,0.405331,0.737934,0.605976,0.011052,0.869296,0.127546,0.321581
2,0.618599,0.674106,0.621795,0.719432,0.152462,0.230517,0.995657,0.410797,0.67077,0.931003
3,0.786005,0.302693,0.254619,0.802144,0.582265,0.75901,0.933889,0.685893,0.691494,0.982817
4,0.400326,0.975319,0.930923,0.440904,0.921014,0.237703,0.439559,0.673244,0.096202,0.339681
5,0.716753,0.872795,0.850293,0.315631,0.0724927,0.569305,0.140424,0.362153,0.0462153,0.741196
6,0.4253,0.725392,0.909002,0.0443817,0.713744,0.802987,0.462297,0.745621,0.878658,0.491345
7,0.433204,0.873358,0.380013,0.071044,0.391667,0.959372,0.353108,0.567884,0.0296113,0.884311
8,0.867481,0.705642,0.766446,0.221053,0.628852,0.623434,0.370704,0.655649,0.905203,0.376352
9,0.291824,0.582192,0.770054,0.396233,0.418564,0.601758,0.769188,0.159684,0.472157,0.621465


In [47]:
mapcols(mean, x)

Row,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64
1,0.575613,0.652607,0.596068,0.366428,0.530013,0.541085,0.463262,0.594963,0.429325,0.576051


### Mapping rows and columns using `eachcol` and `eachrow`

In [48]:
map(mean, eachcol(x)) # map a function over each column and return a vector

10-element Vector{Float64}:
 0.5756134191032852
 0.6526073671309209
 0.5960680866937823
 0.36642789908050327
 0.5300125978621322
 0.5410846992866727
 0.463262310803746
 0.5949634420188546
 0.4293252799906483
 0.5760506426153037

In [49]:
# an iteration returns a Pair with column name and values
foreach(c -> println(c[1], ": ", mean(c[2])), pairs(eachcol(x)))

x1: 0.5756134191032852
x2: 0.6526073671309209
x3: 0.5960680866937823
x4: 0.36642789908050327
x5: 0.5300125978621322
x6: 0.5410846992866727
x7: 0.463262310803746
x8: 0.5949634420188546
x9: 0.4293252799906483
x10: 0.5760506426153037


In [50]:
# now the returned value is DataFrameRow which works as a NamedTuple but is a view to a parent DataFrame
map(r -> r.x1/r.x2, eachrow(x))

10-element Vector{Float64}:
 1.4075067750424386
 0.9176589891533926
 2.5967032651494586
 0.4104568495208197
 0.8212155805124443
 0.5863046179661139
 0.49602140885025114
 1.2293508223337868
 0.5012511739992234
 1.6002497733522727

In [51]:
# it prints like a data frame, only the caption is different so that you know the type of the object
er = eachrow(x)

Row,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64
1,0.634498,0.450796,0.364021,0.405331,0.737934,0.605976,0.011052,0.869296,0.127546,0.321581
2,0.618599,0.674106,0.621795,0.719432,0.152462,0.230517,0.995657,0.410797,0.67077,0.931003
3,0.786005,0.302693,0.254619,0.802144,0.582265,0.75901,0.933889,0.685893,0.691494,0.982817
4,0.400326,0.975319,0.930923,0.440904,0.921014,0.237703,0.439559,0.673244,0.096202,0.339681
5,0.716753,0.872795,0.850293,0.315631,0.0724927,0.569305,0.140424,0.362153,0.0462153,0.741196
6,0.4253,0.725392,0.909002,0.0443817,0.713744,0.802987,0.462297,0.745621,0.878658,0.491345
7,0.433204,0.873358,0.380013,0.071044,0.391667,0.959372,0.353108,0.567884,0.0296113,0.884311
8,0.867481,0.705642,0.766446,0.221053,0.628852,0.623434,0.370704,0.655649,0.905203,0.376352
9,0.291824,0.582192,0.770054,0.396233,0.418564,0.601758,0.769188,0.159684,0.472157,0.621465


In [52]:
er.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.6344983698478375
 0.6185993991889149
 0.7860048695713956
 0.40032622222829395
 0.7167525181736809
 0.425300409621153
 0.43320414313615463
 0.8674813387722898
 0.2918242412448704
 0.5821426792482611

In [53]:
# it prints like a data frame, only the caption is different so that you know the type of the object
ec = eachcol(x)

Row,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64
1,0.634498,0.450796,0.364021,0.405331,0.737934,0.605976,0.011052,0.869296,0.127546,0.321581
2,0.618599,0.674106,0.621795,0.719432,0.152462,0.230517,0.995657,0.410797,0.67077,0.931003
3,0.786005,0.302693,0.254619,0.802144,0.582265,0.75901,0.933889,0.685893,0.691494,0.982817
4,0.400326,0.975319,0.930923,0.440904,0.921014,0.237703,0.439559,0.673244,0.096202,0.339681
5,0.716753,0.872795,0.850293,0.315631,0.0724927,0.569305,0.140424,0.362153,0.0462153,0.741196
6,0.4253,0.725392,0.909002,0.0443817,0.713744,0.802987,0.462297,0.745621,0.878658,0.491345
7,0.433204,0.873358,0.380013,0.071044,0.391667,0.959372,0.353108,0.567884,0.0296113,0.884311
8,0.867481,0.705642,0.766446,0.221053,0.628852,0.623434,0.370704,0.655649,0.905203,0.376352
9,0.291824,0.582192,0.770054,0.396233,0.418564,0.601758,0.769188,0.159684,0.472157,0.621465


In [54]:
ec.x1 # you can access columns of a parent data frame directly

10-element Vector{Float64}:
 0.6344983698478375
 0.6185993991889149
 0.7860048695713956
 0.40032622222829395
 0.7167525181736809
 0.425300409621153
 0.43320414313615463
 0.8674813387722898
 0.2918242412448704
 0.5821426792482611

### Transposing

you can transpose a data frame using `permutedims`:

In [55]:
df = DataFrame(reshape(1:12, 3, 4), :auto)

Row,x1,x2,x3,x4
,Int64,Int64,Int64,Int64
1,1,4,7,10
2,2,5,8,11
3,3,6,9,12


In [56]:
permutedims(df)

Row,x1,x2,x3
,Int64,Int64,Int64
1,1,2,3
2,4,5,6
3,7,8,9
4,10,11,12


In [57]:
df.names = ["a", "b", "c"]

3-element Vector{String}:
 "a"
 "b"
 "c"

In [58]:
permutedims(df, :names)

Row,names,a,b,c
,String,Int64,Int64,Int64
1,x1,1,2,3
2,x2,4,5,6
3,x3,7,8,9
4,x4,10,11,12
